version: "3"

services:
  docker-dashboard:
    container_name: docker-dashboard
    build:
      context: .
    ports:
      - "8091:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
